services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.4.0
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlruns/mlflow.db --default-artifact-root /mlruns

  mlpipeline:
    build: .
    depends_on:
      - mlflow
    volumes:
      - .:/app
    working_dir: /app